-- Anonymous visitor notes attached to places.
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.places(id) on delete cascade,
  nickname text,
  content text not null,
  created_at timestamptz not null default now(),
  constraint comments_content_length check (
    char_length(btrim(content)) between 1 and 500
  )
);

create index if not exists idx_comments_place_id
  on public.comments(place_id);

alter table public.comments enable row level security;

revoke all on table public.comments from anon;
grant select on table public.comments to anon;
grant insert (place_id, nickname, content) on table public.comments to anon;
grant usage on sequence public.comments_id_seq to anon;

create policy "Anonymous users can read comments"
  on public.comments
  for select
  to anon
  using (true);

create policy "Anonymous users can create comments"
  on public.comments
  for insert
  to anon
  with check (char_length(btrim(content)) between 1 and 500);
